kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

steps:
- name: build
  commands:
  - ./Build/build.sh
  
  # -quit -batchmode -projectPath . -executeMethod  
