kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

steps:
- name: build
  commands:
  - echo Starting the build 
  - .\Build\build.bat
  - echo Build ended 
